sudo: required
services:
  - docker

before_install:
  - docker build -t hcgoranson/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hcgoranson/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-north-1-345993156741"
  bucket_path: "docker-react"
  on:
    branch: master
accees_key_id: "$AWS_ACCES_KEY"
secret_acces_key:
  secure: "$AWS_SECRET_KEY"
